global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: medai-a1-api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: medai-a1-evidently
    metrics_path: /metrics
    static_configs:
      - targets: ['evidently-worker:8001']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']